name: Deploy Panel

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/afshari-panel:latest .

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/afshari-panel:latest

      - name: Deploy to server
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull & Run on Server
        run: |
          ssh -o StrictHostKeyChecking=no root@89.32.249.114 << 'EOF'
            set -e

            echo "ðŸ›‘ Stopping old container..."
            docker stop panel || true
            docker rm panel || true

            echo "â¬‡ï¸ Pulling new image..."
            docker pull hamidrezahz98/afshari-panel:latest

            echo "ðŸš€ Running new version..."
            docker run -d \
              --name panel \
              -p 3001:3001 \
              --restart always \
              hamidrezahz98/afshari-panel:latest

            echo "âœ… PANEL DEPLOYED"
          EOF
