name: Deploy Panel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Build & Run Container on Server
        run: |
          ssh -o StrictHostKeyChecking=no root@89.32.249.114 << 'EOF'
            cd /var/www/afshari-gallery/panel || exit 1

            git pull origin master

            docker stop panel || true
            docker rm panel || true
            docker rmi panel || true

            docker build -t panel .

            docker run -d \
              --name panel \
              -p 3001:3001 \
              --restart always \
              panel
          EOF
